### ISSUE TITLE
Can't resize icons with v 5.3

### ISSUE THREAD

**Issue by Zerokk** [michaelbazos/angular-feather#11]
I tried styling icons via CSS classes, just as in the README example, but icons won't resize; their parent container just get bigger, while the actual SVG image stays the same. 

This is happening in Firefox at least.

**Comment by michaelbazos** [comment]
Thanks for reporting @Zerokk 

Seems I cannot reproduce the issue. Does the [demo](https://stackblitz.com/edit/angular-feather?file=app%2Fapp.component.html) work for you in Firefox ?
Is it possible to reproduce the issue in stackblitz ?

**Comment by michaelbazos** [comment]
@Zerokk any update on this?

**Comment by michaelbazos** [comment]
Closing as non reproducible
