### ISSUE TITLE
Missing mouse-pointer?

### ISSUE THREAD

**Issue by initplatform** [michaelbazos/angular-feather#12]
..and looks like 5 more. 
angular-feather.d.ts lists out 268 icons, but <https://feathericons.com> shows 274 icons total...

**Comment by michaelbazos** [comment]
Thanks for reporting it @initplatform

I'll update the library so as to include those new additions

**Comment by michaelbazos** [comment]
There you go, please update to latest

New additions are:

```html
<i-figma>
<i-frown>
<i-key>
<i-meh>
<i-mouse-pointer>
<i-pen-tool>
<i-smile>
<i-x-octagon>
```
