### ISSUE TITLE
Icon does not update

### ISSUE THREAD

**Issue by pauldraper** [michaelbazos/angular-feather#18]
When the name input changes, the icon does not update.

I imagine(?) this was the reason for going from `<i-heart></i-heart>` to `<i-feather [name]="'heart'"></i-feather>`, but it doesn't work.

**Comment by emanzuetaj** [comment]
@pauldraper agreed, my *workaround* to this has been to use a timeout such as 
```
      this.hideIcon = true;
      this.icon = 'heart';
      setTimeout(() => {
        this.hideIcon = false;
      });
```

**Comment by pauldraper** [comment]
My workaround is

```
<ng-container *ngFor="let n of [name]">
  <i-feather
    [name]="n"
  ></i-feather>
</ng-container>
```

**Comment by michaelbazos** [comment]
Thank you for the report & suggested workarounds @pauldraper and @emanzuetaj  

I was able to reproduce the issue and push a fix. 

It should work without workaround in version 6.0.2.

**Comment by michaelbazos** [comment]
Updated the demo to use the version with the fix:

https://stackblitz.com/edit/angular-feather?file=src%2Fapp%2Fapp.component.html
