### ISSUE TITLE
Can't use programmatically 

### ISSUE THREAD

**Issue by denistrofimov** [michaelbazos/angular-feather#2]
Let say we have menu which consist of items with icon and text. By angular concepts we should define array of objects that represents each menu item. Then we go through this items in *ngFor loop and print  items one by one. 
```
<button menuClose ion-item detail-none *ngFor="let p of pages" (click)="openPage(p)">
        <ion-icon [name]="p.icon"></ion-icon>
        {{p.title}}
</button>
```
How we should implement this behaviour with angular-feather? ngSwitch?

**Comment by andrewjrhill** [comment]
October 2017? I am surprised this hasn't been addressed yet. It's pretty important to be able to programmatically adjust icons as needed. Hopefully this gets an answer.

**Comment by michaelbazos** [comment]
Apologies for the letting this long aside.

This use-case is now solved in v6 with the move to a single-component.

Example usage:

*some.component.html*
```html
<ng-container *ngFor="let icon of icons">
    <i-feather [name]="icon.name" [ngClass]="icon.class"></i-feather>
</ng-container>
```

*some.component.ts*
```js
icons = [
    { name: 'camera', class: 'big' },
    { name: 'heart', class: 'big fill-red' },
    { name: 'github', class: 'big fill-green' },
]
```

Full example visible in **[the demo application](https://stackblitz.com/edit/angular-feather?file=src%2Fapp%2Fapp.component.ts)**
