### ISSUE TITLE
FeatureRequest: Tool Icon

### ISSUE THREAD

**Issue by jabali2004** [michaelbazos/angular-feather#23]
It would be great if the Tool Icon could be added to the List..., 

`export const Tool = "<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tool">
  <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path>
</svg>";
`

**Comment by michaelbazos** [comment]
@jabali2004 

Thanks for the notice. The tool icon is now available in latest version (currently `6.0.3`) 

```html
<i-feather name="tool"></i-feather>
```
