### ISSUE TITLE
I can't get the icons by its name -> Error not found : iconName

### ISSUE THREAD

**Issue by fflores-origin** [michaelbazos/angular-feather#28]
I can't get the icons by its name. 
Looking the error, I saw that the array is being build with index numbers instead of their alias name.
I'm using angular 8.0.3, I don't think this could be the problem.

![image](https://user-images.githubusercontent.com/12190862/68161085-db597a00-ff33-11e9-89a7-99169d941f67.png)

icons.module.ts : 

`
import { NgModule } from '@angular/core';
import { FeatherModule } from 'angular-feather';
import {
  Slash,
  Info,
  Check,
  Home,
  Github,
  Archive,
  Heart
} from 'angular-feather/icons';

const icons = [Slash, Info, Check, Home, Github, Archive, Heart];

@NgModule({
  imports: [FeatherModule.pick(icons)],
  exports: [FeatherModule]
})
export class IconsModule {}
`

`   <i-feather name="3" ></i-feather>      Working`
`<i-feather name="home" ></i-feather> Not Working`

**Comment by michaelbazos** [comment]
@fflores-origin 

It's a bit subtle, but that is because the variable you pass to `FeatherModule.pick(...)` should be an object and not an array:

    const icons = { Slash, Info, Check, Home, Github, Archive, Heart };

which in ES6 is a shorthand notation for:

```ts
const icons = {
  'Slash': Slash, 
  'Info': Info,
  'Check': Check, 
  'Home': Home
...
};
```

**Comment by fflores-origin** [comment]
Ohhh thanks dude!! That solved my problem. I didnt' realize that I used an array!!
