### ISSUE TITLE
Request to update the outdated Dev-Dependencies for Angular 8/9

### ISSUE THREAD

**Issue by Premiermaddy** [michaelbazos/angular-feather#29]
The NPM package manager is showing the icons's dev dependencies are outdated. As, we re relying on feather icons and our recent efforts to upgrade angular application are blocked by this issue. 
https://david-dm.org/michaelbazos/angular-feather?type=dev
![image](https://user-images.githubusercontent.com/56090035/68425224-aa678800-0173-11ea-8585-f9eb97c2e001.png)

**Comment by michaelbazos** [comment]
Those are dependencies used only at development time. They are not installed when you install the npm package `angular-feather`, so it should not be a blocker to update the parent application.

Furthermore, `npm audit` on latest `angular-feather` finds no vulnerability.

**Comment by michaelbazos** [comment]
Closing issues, as I've updated devDependencies that could be updated.
