### ISSUE TITLE
Possible to add custom icons?

### ISSUE THREAD

**Issue by spoon252** [michaelbazos/angular-feather#31]
Hi, thanks for the library, it works very well in Angular 7 for me. One question would be if it's possible to import my own svg icons in this library, because otherwise they have to be requested here right?

Thanks

**Comment by michaelbazos** [comment]
Hi @spoon252,

You can for sure use your own SVG icons. All you have to do is to associate the svg code with a string property key, that will be used to identify the icon:

**icons.module.ts*
```ts
// Heart and Github svg icons are from the angular-feather
import { Heart, Github } from 'angular-feather/icons';

// Camera svg is your custom icon
const icons = {
  Camera: `<svg ...>...</svg>`,
  Heart: Heart,
  Github: Github
};
```

Or, for readability purpose, you may want to store your custom svg in a separate file:

**myCamera.ts**
```ts
export MyCamera = `<svg ...>...</svg>`;
```

**icons.module.ts*
```ts
// Heart and Github svg icons are from the angular-feather
import { Heart, Github } from 'angular-feather/icons';
import { MyCamera } from './myCamera';

// Camera svg is your custom icon
const icons = {
  Camera: MyCamera,
  Heart: Heart,
  Github: Github
};
```

Hope this helps

**Comment by spoon252** [comment]
Thank you very much!
