### ISSUE TITLE
Live demo is not working!

### ISSUE THREAD

**Issue by dalejodc** [michaelbazos/angular-feather#32]
Hey @michaelbazos!

Maybe you already know it, but I just wanted to notify that the [live demo](https://stackblitz.com/edit/angular-feather?file=src%2Fapp%2Fapp.component.html) cited in in the _**README.md**_ and **npm** package is not working.

**Comment by dalejodc** [comment]
My bad @michaelbazos. The live demo is working as expected. I'm so sorry!

**Comment by michaelbazos** [comment]
Hi @dalejodc ,

No worries, this happens :)

Happy New Year!
