### ISSUE TITLE
No suitable injection token for parameter 'elem' of class 'FeatherComponent'

### ISSUE THREAD

**Issue by MaliahRajan** [michaelbazos/angular-feather#35]
0% compiling
Compiling angular-feather : es2015 as esm2015

ERROR in No suitable injection token for parameter 'elem' of class 'FeatherComponent'.
no type or decorator
 
Dependency

{
  "name": "angular",
   "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.26",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "@types/c3": "^0.7.4",
    "angular-feather": "^6.0.2",
    "angular-font-awesome": "^3.1.2",
    "c3": "^0.7.15",
    "chart.js": "^2.9.3",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "ng2-charts": "^2.3.0",
    "ngx-csv": "^0.3.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.11.1",
    "xlsx": "^0.15.6",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.26",
    "@angular/cli": "^8.3.26",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by michaelbazos** [comment]
Thanks for the report @MaliahRajan 

Can you confirm the resolution with the version 6.0.9 ?
