### ISSUE TITLE
NullInjectorError: No provider for Icons

### ISSUE THREAD

**Issue by koficypher** [michaelbazos/angular-feather#48]
Node V:  14.17.0
Npm V: 6.14.13
NG CLI: 12
Feather Icon: 6.1.0
OS: Windows

I have a feature module called Core Module that has components for the layout of my application. Such components are imported into a layout module for different layout styles for the application. Feather icons is imported into the Core module because the sidebar makes use of them. Now when i run ng serve or npm start i get the this error:
`ERROR NullInjectorError: R3InjectorError(AppModule)[Icons -> Icons -> Icons]: 
  NullInjectorError: No provider for Icons
`

Now by this i understand that one of my imports i.e. the Feather Icon module is missing a provider but it isnt clear where i need to provide this class or service and which particular class i need to provide.

**Comment by echle** [comment]
I dont think its a problem of the library but maybe I missunderstand your usecase.

You will need to import the FeatherModule in each module you are using them. Usually you establish something like a sharedModule, that imports and exports such commonly used modules. So you would need to import the shared module into you core module and your layout module.

**Comment by sandeep18051989** [comment]
when you are planning to launch feather package compatible with angular >13

**Comment by michaelbazos** [comment]
@sandeep18051989 It has been released, please see version library versions >= 6.2.0
