### ISSUE TITLE
Make icons resizable.

### ISSUE THREAD

**Issue by JamboBuenna** [michaelbazos/angular-feather#5]
I couldn't see from the source code or docs how to make the icons resizable. 
Is this currently possible, or are they fixed size. I can't seem to resize them in external css either.

Making the example below always 24 by 24
`<i-log-in></i-log-in>`

**Comment by michaelbazos** [comment]
@JamboBuenna 
Apologies for the delay. Please update the version of angular-feather (current is 5.3.0) and check out the updated README which contains information about styling as well as a link to a demo.
Let me know if you run into issues or if something is unclear.

**Comment by JamboBuenna** [comment]
Thanks bud :-) Apologies in the delay in seeing this!
