### ISSUE TITLE
feather package not compatible with angular versions > 13

### ISSUE THREAD

**Issue by sandeep18051989** [michaelbazos/angular-feather#51]
Hi,
I want to use feather package with my angular app using version 13.0.3 (latest), can you please upgrade it ?

**Comment by sandeep18051989** [comment]
any update please ?

**Comment by TomasKostadinov** [comment]
@sandeep18051989 I asked the developer that upgraded the library to angular 12 on how to do this. (See https://github.com/michaelbazos/angular-feather/pull/50#issuecomment-1001498641)

Maybe we all can work together on upgrading the library.

**Comment by anikets43** [comment]
> @sandeep18051989 I asked the developer that upgraded the library to angular 12 on how to do this. (See [#50 (comment)](https://github.com/michaelbazos/angular-feather/pull/50#issuecomment-1001498641))
> 
> Maybe we all can work together on upgrading the library.

@TomasKostadinov 
Please check this
https://github.com/michaelbazos/angular-feather/pull/52

**Comment by TheCodingWaffle** [comment]
@anikets43 thanks for bumping the version. I just updated several projects to 13 and this will be a nice post holiday present.

**Comment by michaelbazos** [comment]
A new version of the library was published to the npm registry
