### ISSUE TITLE
Providing an alt

### ISSUE THREAD

**Issue by AbdealiLoKo** [michaelbazos/angular-feather#54]
Is there any way for me to provide an "alt" value for the icons when I use `i-feather` ?

**Comment by meppig** [comment]
SVG content will be inlined and if you pick the images (`FeatherModule.pick({})`) before using them then there shouldnt be a case where an alt text is needed.
If it's for accessibility you could set the `aria-label` attribute on the `i-feather` tag, see this discussion here: https://stackoverflow.com/a/4756461
